#!/usr/bin/env python3
"""Generate blank RCA report template for manual review."""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from _shared import now_iso, output_json, parse_args


def _build_blank_template(params):
    title = params.get("title", f"RCA Template — {now_iso()[:10]}")
    service = params.get("service", "{{SERVICE_NAME}}")
    severity = params.get("severity", "{{SEVERITY}}")
    author = params.get("author", "{{AUTHOR}}")

    template = "\n".join(
        [
            f"# Root Cause Analysis — {title}",
            "",
            "## Document Control",
            "",
            "| Field | Value |",
            "|-------|-------|",
            f"| **Incident Title** | {title} |",
            "| **Date of Incident** | {{YYYY-MM-DD}} |",
            "| **Date of Report** | {{YYYY-MM-DD}} |",
            f"| **Report Author** | {author} |",
            "| **Reviewers** | {{REVIEWER_1}}, {{REVIEWER_2}} |",
            f"| **Severity** | {severity} |",
            f"| **Service(s) Affected** | `{service}` |",
            "| **Workspace ID** | `{{WORKSPACE_ID}}` |",
            "| **Alert ID** | `{{ALERT_ID}}` |",
            "| **Status** | Draft / Under Review / Final |",
            "",
            "---",
            "",
            "## 1. Executive Summary",
            "",
            "> Provide a 3-5 sentence summary that a non-technical executive can understand.",
            "> Include: what broke, who was affected, for how long, and current status.",
            "",
            "{{EXECUTIVE_SUMMARY}}",
            "",
            "---",
            "",
            "## 2. Impact Assessment",
            "",
            "### 2.1 User Impact",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            "| Estimated users affected | {{USER_COUNT}} |",
            "| Error rate during incident | {{ERROR_RATE}} |",
            "| Requests failed | {{FAILED_REQUESTS}} |",
            "| Revenue impact (if applicable) | {{REVENUE_IMPACT}} |",
            "",
            "### 2.2 Service Impact",
            "",
            "| Metric | Before | During | After |",
            "|--------|--------|--------|-------|",
            "| P50 latency | {{P50_BEFORE}} | {{P50_DURING}} | {{P50_AFTER}} |",
            "| P99 latency | {{P99_BEFORE}} | {{P99_DURING}} | {{P99_AFTER}} |",
            "| Error rate | {{ERR_BEFORE}} | {{ERR_DURING}} | {{ERR_AFTER}} |",
            "| Throughput (req/s) | {{TPS_BEFORE}} | {{TPS_DURING}} | {{TPS_AFTER}} |",
            "| CPU utilization | {{CPU_BEFORE}} | {{CPU_DURING}} | {{CPU_AFTER}} |",
            "| Memory utilization | {{MEM_BEFORE}} | {{MEM_DURING}} | {{MEM_AFTER}} |",
            "",
            "### 2.3 Blast Radius",
            "",
            "```mermaid",
            "graph TD",
            "    ROOT['Root Cause<br/>{{ROOT_CAUSE}}'] --> SVC1['{{PRIMARY_SERVICE}}<br/>Direct Impact']",
            f"    ROOT --> SVC2['{service}<br/>Direct Impact']",
            "    SVC1 --> DOWN1['{{DOWNSTREAM_1}}<br/>Degraded']",
            "    SVC1 --> DOWN2['{{DOWNSTREAM_2}}<br/>Degraded']",
            "    SVC2 --> DOWN3['{{DOWNSTREAM_3}}<br/>Healthy']",
            "",
            "    style ROOT fill:#ef4444,color:#fff",
            "    style SVC1 fill:#f97316,color:#fff",
            "    style SVC2 fill:#f97316,color:#fff",
            "    style DOWN1 fill:#eab308,color:#000",
            "    style DOWN2 fill:#eab308,color:#000",
            "    style DOWN3 fill:#22c55e,color:#fff",
            "```",
            "",
            "---",
            "",
            "## 3. 5W Analysis",
            "",
            "### What Happened?",
            "",
            "> Describe the observable symptom. What did the monitoring show?",
            "> What did users experience? What did the logs say?",
            "",
            "{{WHAT_HAPPENED}}",
            "",
            "### Where Did It Happen?",
            "",
            "> Specify the exact service, namespace, cluster, region, database, or",
            "> infrastructure component. Include resource identifiers.",
            "",
            "| Dimension | Value |",
            "|-----------|-------|",
            "| Service | `{{SERVICE}}` |",
            "| Namespace | `{{NAMESPACE}}` |",
            "| Cluster | `{{CLUSTER}}` |",
            "| Region | `{{REGION}}` |",
            "| Database | `{{DATABASE}}` |",
            "| Node | `{{NODE}}` |",
            "",
            "### When Did It Happen?",
            "",
            "| Milestone | Timestamp (UTC) |",
            "|-----------|----------------|",
            "| First anomaly detected | {{T_FIRST_ANOMALY}} |",
            "| Alert fired | {{T_ALERT_FIRED}} |",
            "| On-call notified | {{T_NOTIFY}} |",
            "| Investigation started | {{T_INVESTIGATE}} |",
            "| Root cause identified | {{T_ROOT_CAUSE}} |",
            "| Remediation proposed | {{T_REMEDIATE_PROPOSE}} |",
            "| Remediation approved | {{T_REMEDIATE_APPROVE}} |",
            "| Remediation executed | {{T_REMEDIATE_EXEC}} |",
            "| Service restored | {{T_RESTORED}} |",
            "| Total MTTR | {{MTTR_DURATION}} |",
            "",
            "### Why Did It Happen?",
            "",
            "> Explain the root cause in technical detail. What condition, bug,",
            "> misconfiguration, or external event triggered the incident?",
            "",
            "{{WHY_IT_HAPPENED}}",
            "",
            "### How Was It Resolved?",
            "",
            "> Describe the exact remediation action taken. Be specific enough",
            "> that someone could reproduce the fix.",
            "",
            "{{HOW_RESOLVED}}",
            "",
            "---",
            "",
            "## 4. Timeline",
            "",
            "```mermaid",
            "timeline",
            f"    title {title}",
            "    section Detection",
            "        {{TIME_1}} : First anomaly detected",
            "        {{TIME_2}} : Alert fired",
            "        {{TIME_3}} : Triage classified as CRITICAL",
            "    section Investigation",
            "        {{TIME_4}} : Investigator queries metrics",
            "        {{TIME_5}} : Investigator queries logs",
            "        {{TIME_6}} : Investigator queries traces",
            "        {{TIME_7}} : Root cause hypothesis formed",
            "    section Verification",
            "        {{TIME_8}} : Reviewer starts independent check",
            "        {{TIME_9}} : Reviewer confirms hypothesis",
            "    section Resolution",
            "        {{TIME_10}} : Remediation proposed",
            "        {{TIME_11}} : Human approves via Telegram",
            "        {{TIME_12}} : Action executed",
            "        {{TIME_13}} : Service restored",
            "```",
            "",
            "### Detailed Event Log",
            "",
            "| # | Timestamp | Event | Source | Owner | Detail |",
            "|---|-----------|-------|--------|-------|--------|",
            "| 1 | {{TS}} | {{EVENT}} | {{SRC}} | {{OWNER}} | {{DETAIL}} |",
            "",
            "---",
            "",
            "## 5. Root Cause Deep Dive",
            "",
            "### 5.1 Contributing Factors",
            "",
            "| Factor | Type | Contribution | Evidence |",
            "|--------|------|-------------|----------|",
            "| {{FACTOR_1}} | Code / Config / Infra / External | {{CONTRIBUTION}} | {{EVIDENCE}} |",
            "",
            "### 5.2 Why Defenses Did Not Catch It",
            "",
            "> Explain why existing monitoring, alerts, or tests did not prevent",
            "> or detect this issue earlier.",
            "",
            "{{WHY_NOT_CAUGHT}}",
            "",
            "### 5.3 Causal Chain",
            "",
            "```mermaid",
            "flowchart TD",
            "    A['{{TRIGGER_EVENT}}'] --> B['{{INTERMEDIATE_1}}']",
            "    B --> C['{{INTERMEDIATE_2}}']",
            "    C --> D['{{OBSERVED_SYMPTOM}}']",
            "    D --> E['{{USER_IMPACT}}']",
            "",
            "    style A fill:#ef4444,color:#fff",
            "    style E fill:#f97316,color:#fff",
            "```",
            "",
            "---",
            "",
            "## 6. Lessons Learned",
            "",
            "### 6.1 What Went Well",
            "",
            "- [ ] {{WENT_WELL_1}}",
            "- [ ] {{WENT_WELL_2}}",
            "- [ ] {{WENT_WELL_3}}",
            "",
            "### 6.2 What Could Be Improved",
            "",
            "- [ ] {{IMPROVE_1}}",
            "- [ ] {{IMPROVE_2}}",
            "- [ ] {{IMPROVE_3}}",
            "",
            "### 6.3 Where We Got Lucky",
            "",
            "- [ ] {{LUCKY_1}}",
            "- [ ] {{LUCKY_2}}",
            "",
            "---",
            "",
            "## 7. Action Items",
            "",
            "| # | Action | Owner | Priority | Due Date | Status | Jira/Trello |",
            "|---|--------|-------|----------|----------|--------|-------------|",
            "| 1 | {{ACTION_1}} | {{OWNER_1}} | P1 | {{DUE_1}} | Pending | {{TICKET_1}} |",
            "| 2 | {{ACTION_2}} | {{OWNER_2}} | P2 | {{DUE_2}} | Pending | {{TICKET_2}} |",
            "| 3 | {{ACTION_3}} | {{OWNER_3}} | P2 | {{DUE_3}} | Pending | {{TICKET_3}} |",
            "| 4 | {{ACTION_4}} | {{OWNER_4}} | P3 | {{DUE_4}} | Pending | {{TICKET_4}} |",
            "",
            "---",
            "",
            "## 8. Jira / Trello Ticket Summary",
            "",
            "### Jira Ticket",
            "",
            "| Field | Value |",
            "|-------|-------|",
            "| Project | {{JIRA_PROJECT}} |",
            "| Issue Type | Incident |",
            f"| Summary | [RCA] {title} |",
            f"| Labels | rca, {service}, {severity.lower()} |",
            "| Description | See Executive Summary above |",
            "",
            "### Trello Card",
            "",
            "| Field | Value |",
            "|-------|-------|",
            f"| Title | [RCA] {title} |",
            "| List | Incident Review |",
            f"| Labels | {severity.lower()}, rca |",
            "| Checklist | Execute remediation, Review thresholds, Update MEMORY.md, Schedule postmortem |",
            "",
            "---",
            "",
            "## 9. Approval",
            "",
            "| Role | Name | Date | Signature |",
            "|------|------|------|-----------|",
            "| Incident Commander | {{IC_NAME}} | {{DATE}} | |",
            "| Technical Lead | {{TL_NAME}} | {{DATE}} | |",
            "| Engineering Manager | {{EM_NAME}} | {{DATE}} | |",
            "",
            "---",
            "",
            f"*Template generated by TelemetryFlow Hermes Agent on {now_iso()}*",
        ]
    )

    return {
        "report": template,
        "format": "markdown",
        "type": "blank_rca_template",
        "generated_at": now_iso(),
    }


def main():
    args = parse_args()
    result = _build_blank_template(args)
    output_json(result)


if __name__ == "__main__":
    main()
